---
baseURL: https://www.wildernessprime.com/
languageCode: en-us
title: Wilderness Prime
metaDataFormat: yaml
googleAnalytics: UA-135021930-1
languages:
  en:
    languageName: EN
    weight: 1
  fr:
    languageName: FR
    weight: 2
params:
  imgbase: https://res.cloudinary.com/wildernessprime/image/upload
  pagesize: 6

outputs:
  home:
    - HTML
    - RSS

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: rss1

# disqusShortname: wildernessprime