---
baseURL: https://www.wildernessprime.com/
languageCode: en-us
title: Wilderness Prime
metaDataFormat: yaml
googleAnalytics: UA-135021930-1
languages:
  en:
    languageName: EN
    weight: 1
  fr:
    languageName: FR
    weight: 2

disableLanguages: ["fr"]

taxonomies:
  category: categories
  tag: tags
  social: socials 
  
outputs:
  home:
    - HTML
    - RSS

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

params:
  imgbase: https://res.cloudinary.com/wildernessprime/image/upload
  pagesize: 12
  pagetypes:
    - report
    - review

markup:
  goldmark:
    renderer:
      unsafe: true

enableInlineShortcodes: true