---
baseURL: https://www.wildernessprime.com/
languageCode: en-us
title: Wilderness Prime
theme: massively
metaDataFormat: yaml
languages:
  en:
    languageName: EN
    weight: 1
  fr:
    languageName: FR
    weight: 2
taxonomies:
  tag: tags 
  category: categories
  expedition: expeditions
params:
  cloudinary_base_url: https://res.cloudinary.com/wildernessprime/image/upload
  folders: 
    - "reviews"
    - "reports"
