version: 2

jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: cibuilds/hugo:0.62.0
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
      HUGO_DEPLOY_DIR: ~/hugo/deploy
    steps:
      - run: apk update && apk add git rsync
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - deploy:
          name: Deploy to Github Pages
          command: |
            git config --global push.default simple
            git config --global user.email "dave@brophy.uk"
            git config --global user.name "dave"
            git clone -q --branch=gh-pages $CIRCLE_REPOSITORY_URL $HUGO_DEPLOY_DIR
            cd $HUGO_DEPLOY_DIR
            rsync -arv --delete ../public/* .
            git add -f .
            git commit -m "Deploy build $CIRCLE_BUILD_NUM [ci skip]" || true
            git push -f

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
